### PR TITLE
Wrong configuration name was use when a new, non pages record was processed in TCEMain.

### LINKED ISSUE #48: Indexing of new records will crash if the name of the  Indexing Queue Configuration is different from tablename
When you have in your SOLR configuration a index queue item for a table:
```
plugin.tx_solr.index.queue {
    news {
        table = tt_news
        fields {
            ...
        }
    }
}
```
the indexing of a new record for this table will insert the wrong indexing configuration name (indexing_configuration) in the tx_solr_indexqueue_item table. It will insert "tt_news" instead of "news" and with this indexing_configuration the Indexer gets NULL instead of an array of the itemIndexingConfiguration because there is no configuration ```plugin.tx_solr.index.queue.tt_news.fields```.

The problem is in the Hook "processDatamap_afterDatabaseOperations" of ext-solr/Classes/IndexQueue/RecordMonitor.php line 232:
```PHP
if ($this->isEnabledRecord($recordTable, $record)) {
	$configurationName = NULL;
	if ($recordTable !== 'pages') {
/* #232 */		$configurationName = $this->getIndexingConfigurationName($table, $uid);
	}
	$this->indexQueue->updateItem($recordTable, $recordUid, $configurationName);
}
```
To get the correct indexing_configuration (```$configurationName```) you have to use ```$recordTable``` and ```$recordUid```:
```PHP
if ($this->isEnabledRecord($recordTable, $record)) {
	$configurationName = NULL;
	if ($recordTable !== 'pages') {
/* #232 Changed: */		$configurationName = $this->getIndexingConfigurationName($recordTable, $recordUid);
	}
	$this->indexQueue->updateItem($recordTable, $recordUid, $configurationName);
}
```

Do I see that right?

### PR DESCRIPTION
**Pull request by timoschmidt**
- Fixed bug in RecordMonitor
- Added regression Test and improved Testing Codebase

Fixes #48

### CODE REVIEW

**Comment by irnnr** [comment]
As a bugfix this can go into 3.1.1 as well. Simply needs to be cherry picked after merging into master.

**Comment by irnnr** [comment]
Will try to review this weekend.

File: Tests/Functional/IndexQueue/Fixtures/fake_extension_table.sql [hunk 1]
```diff
@@ -0,0 +1,31 @@
+drop table if exists tx_fakeextension_domain_model_foo;
```
Comment (irnnr) [inline Tests/Functional/IndexQueue/Fixtures/fake_extension_table.sql]: Please use uppercase SQL keywords

File: Tests/Functional/IndexQueue/RecordMonitorTest.php [hunk 2]
```diff
@@ -121,4 +121,46 @@ public function canUpdateRootPageRecordWithoutSQLErrorFromMountPages()
...
+
+    /**
+     * Regression test for issue #48. Indexing of new records will crash if the name of the Indexing
+     * Queue Configuration is different from tablename
+     * @see https://github.com/TYPO3-Solr/ext-solr/issues/48
+     * @test
+     */
+    public function canUseCorrectIndexingConfigurationForANewNonPagesRecord()
+    {
+        // create fake extension database table and tca
```
Comment (irnnr) [inline Tests/Functional/IndexQueue/RecordMonitorTest.php]: really minor nitpick, pleas use uppercase TCA, even in comments

File: Tests/Functional/IndexQueue/Fixtures/fake_extension_tca.php [hunk 3]
```diff
@@ -0,0 +1,162 @@
+<?php
+
+return [
```
Comment (irnnr) [inline Tests/Functional/IndexQueue/Fixtures/fake_extension_tca.php]: Please do not use short array syntax (yet).
If a change makes sense to be applied to the 3.1.x branch it needs to use explicit `array()` syntax as the tests for 3.1 are executed against PHP versions that do not support the short syntax.

File: Tests/Functional/FunctionalTest.php [hunk 4]
```diff
@@ -64,20 +64,59 @@ public function setUp()
...
+    protected function importDumpFromFixture($fixtureName)
+    {
+        /** @var $database  \TYPO3\CMS\Core\Database\DatabaseConnection */
+        $database = $GLOBALS['TYPO3_DB'];
+        $database->debugOutput = true;
+
+        $dumpContent = $this->getFixtureContent($fixtureName);
+        $dumpContent = str_replace(array("\r", "\n"), '', $dumpContent);
+
+        $queries = explode(";", $dumpContent);
```
Comment (irnnr) [inline Tests/Functional/FunctionalTest.php]: Always use single quotes

**Comment by irnnr** [comment]
Also, please make sure to have a newline at the end of a file

File: Tests/Functional/FunctionalTest.php [hunk 5]
```diff
@@ -64,20 +64,59 @@ public function setUp()
...
     {
         return $this->getRuntimeDirectory() . '/Fixtures/';
     }
 
     /**
+     * Returns the absolute path to a fixture file.
+     *
+     * @return string
+     */
+    protected function getFixturePath($fixtureName)
```
Comment (irnnr) [inline Tests/Functional/FunctionalTest.php]: $fixtureName is missing from phpDoc
